apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-publisher
  template:
    metadata:
      labels:
        app: mqtt-publisher
    spec:
      containers:
      - name: publisher
        image: your-dockerhub/mqtt-publisher:latest
